import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generates a clean, modern PDF transcript on the client using jsPDF
 */
export function exportClientPdf(data) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const primaryColor = [79, 70, 229]; // Indigo
  const darkNavy = [30, 27, 75];
  const slateText = [30, 41, 59];
  const lightBg = [248, 250, 252];

  // 1. Header Banner
  doc.setFillColor(...darkNavy);
  doc.rect(14, 12, 182, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('GPAFlow Academic Transcript', 20, 24);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(199, 210, 254);
  doc.text('Official Semester Grade & GPA Computation Report', 20, 30);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('VERIFIED REPORT', 190, 24, { align: 'right' });

  // 2. Info Box
  doc.setFillColor(...lightBg);
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, 38, 182, 26, 'FD');

  doc.setTextColor(...slateText);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`Student: ${data.studentName || 'Student'}`, 18, 45);
  doc.setFont('helvetica', 'normal');
  doc.text(`Institution: ${data.institution || 'Academic Department'}`, 18, 51);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 18, 57);

  doc.setFont('helvetica', 'bold');
  doc.text(`Semester: ${data.semesterName || 'Current Semester'}`, 110, 45);
  doc.setFont('helvetica', 'normal');
  doc.text(`Scale: ${data.scaleName || 'Standard US 4.0'}`, 110, 51);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text(`Standing: ${data.academicStanding || 'Good Standing'}`, 110, 57);

  // 3. Courses Table
  const tableRows = (data.courses || []).map((c, index) => [
    index + 1,
    c.name || `Course ${index + 1}`,
    c.credits,
    c.grade,
    c.points !== undefined ? c.points : '-',
    c.qualityPoints !== undefined ? c.qualityPoints : '-'
  ]);

  doc.autoTable({
    startY: 68,
    head: [['#', 'Course Title', 'Credits', 'Grade', 'Grade Points', 'Quality Points']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left'
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 70 },
      2: { cellWidth: 22, halign: 'center' },
      3: { cellWidth: 22, halign: 'center' },
      4: { cellWidth: 28, halign: 'center' },
      5: { cellWidth: 30, halign: 'right' }
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: [51, 65, 85]
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    }
  });

  // 4. Summary Box
  const finalY = doc.lastAutoTable.finalY + 8;

  doc.setFillColor(...lightBg);
  doc.setDrawColor(...primaryColor);
  doc.rect(14, finalY, 182, data.cumulative ? 36 : 26, 'FD');

  doc.setTextColor(...primaryColor);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Performance Summary', 18, finalY + 7);

  doc.setTextColor(...slateText);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Semester Credits: ${data.totalCredits}`, 18, finalY + 14);
  doc.text(`Total Quality Points: ${data.totalQualityPoints}`, 18, finalY + 20);

  // Big GPA Badge
  doc.setFillColor(224, 231, 255);
  doc.setDrawColor(129, 140, 248);
  doc.rect(140, finalY + 4, 50, 18, 'FD');

  doc.setTextColor(67, 56, 202);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('SEMESTER GPA', 165, finalY + 9, { align: 'center' });

  doc.setFontSize(13);
  doc.text(`${Number(data.semesterGpa).toFixed(2)}`, 165, finalY + 16, { align: 'center' });

  if (data.cumulative) {
    doc.setDrawColor(203, 213, 225);
    doc.line(18, finalY + 23, 192, finalY + 23);

    doc.setFontSize(8.5);
    doc.setTextColor(...slateText);
    doc.text(`Prior Credits: ${data.cumulative.previousCredits}  |  Prior GPA: ${data.cumulative.previousGpa}`, 18, finalY + 30);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(67, 56, 202);
    doc.text(`Updated CGPA: ${data.cumulative.newCumulativeGpa} (Total Credits: ${data.cumulative.newTotalCredits})`, 105, finalY + 30);
  }

  // 5. Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 15, 196, pageHeight - 15);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(
    'Generated by GPAFlow — Modern Academic GPA & CGPA Engine.',
    105,
    pageHeight - 10,
    { align: 'center' }
  );

  const safeSemester = (data.semesterName || 'Semester').replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`GPAFlow_${safeSemester}_Transcript.pdf`);
}

/**
 * Generates CSV Export
 */
export function exportCsv(data) {
  const headers = ['Course Title', 'Credits', 'Grade', 'Grade Points', 'Quality Points'];
  const rows = (data.courses || []).map(c => [
    `"${(c.name || '').replace(/"/g, '""')}"`,
    c.credits,
    `"${c.grade}"`,
    c.points || 0,
    c.qualityPoints || 0
  ]);

  let csvContent = headers.join(',') + '\n';
  rows.forEach(r => {
    csvContent += r.join(',') + '\n';
  });

  csvContent += `\n"Semester GPA",${data.semesterGpa}\n`;
  csvContent += `"Total Credits",${data.totalCredits}\n`;
  csvContent += `"Total Quality Points",${data.totalQualityPoints}\n`;
  csvContent += `"Academic Standing","${data.academicStanding || 'Good Standing'}"\n`;

  if (data.cumulative) {
    csvContent += `"Previous Credits",${data.cumulative.previousCredits}\n`;
    csvContent += `"Previous GPA",${data.cumulative.previousGpa}\n`;
    csvContent += `"Cumulative GPA",${data.cumulative.newCumulativeGpa}\n`;
    csvContent += `"Cumulative Credits",${data.cumulative.newTotalCredits}\n`;
  }

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `GPAFlow_${(data.semesterName || 'Semester').replace(/\s+/g, '_')}_Summary.csv`;
  document.body.appendChild(a);
  a.click();
  URL.revokeObjectURL(url);
  a.remove();
}
